# syntax=docker/dockerfile:1
ARG RUBY_VERSION=3.2.1
FROM ruby:$RUBY_VERSION-slim

# Instalar dependências do sistema
RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  build-essential \
  curl \
  git \
  libjemalloc2 \
  libvips \
  sqlite3 \
  libsqlite3-dev \
  libyaml-dev \
  pkg-config \
  nodejs \
  npm && \
  rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Configurar diretório de trabalho
WORKDIR /rails

# Configurar ambiente de desenvolvimento
ENV RAILS_ENV=development \
  BUNDLE_PATH="/usr/local/bundle"

# Copiar Gemfile e instalar gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copiar o código da aplicação
COPY . .

# Expor porta do Rails
EXPOSE 3000

# Comando padrão
CMD ["bash"]
